# Generated by Django 3.2.3 on 2021-05-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0003_trasactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trasactions',
            new_name='Transactions',
        ),
    ]
